// MONGODB_URI=
// JWT_SECRET=
// RESEND_API_KEY=
// GOOGLE_IOS_CLIENT_ID=
// GOOGLE_CLIENT_ID=
// GOOGLE_IOS_CLIENT_ID=
// NEXT_PUBLIC_GOOGLE_CLIENT_ID=
// GOOGLE_CLIENT_SECRET=
// BETTER_AUTH_SECRET=
// BETTER_AUTH_URL=
// NODE_ENV=
// NEXT_PUBLIC_APP_URL=
// CLOUDINARY_CLOUD_NAME=
// CLOUDINARY_API_KEY=
// CLOUDINARY_API_SECRET=
// ADMIN_ID=
// RAZORPAY_KEY_ID=
// RAZORPAY_KEY_SECRET=
// NEXT_PUBLIC_RAZORPAY_KEY_ID=



